[libraries]
manifold = { group = "systems.manifold", name = "manifold-preprocessor", version = "2026.1.8" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version = "0.19.3"}
# Unfortunually I can't set a global version ref, because buildSrc-catalog and the kotlin compiler don't like it
fabric-loom = { group = "net.fabricmc", name = "fabric-loom", version = "1.17-SNAPSHOT"}
# Don't know why fabric-loom doesn't need the .gradle.plugin stuff, but this works ig
fabric-loom-remapped = { group = "net.fabricmc.fabric-loom-remap", name = "net.fabricmc.fabric-loom-remap.gradle.plugin", version = "1.17-SNAPSHOT"}
ploceus = { group = "ploceus", name = "ploceus.gradle.plugin", version = "1.17-SNAPSHOT" }
neoforge-gradle = { group = "net.neoforged.gradle.userdev", name = "net.neoforged.gradle.userdev.gradle.plugin", version = "7.1.38" }
mixin-ap = { group = "net.fabricmc", name = "sponge-mixin", version = "0.17.3+mixin.0.8.7" }
mixin = { group = "org.spongepowered", name = "mixin", version = "0.8.7" }
forge-gradle = { group = "net.minecraftforge.gradle", name = "net.minecraftforge.gradle.gradle.plugin", version = "7.0.31" }
forge-renamer = { group = "net.minecraftforge.renamer", name = "net.minecraftforge.renamer.gradle.plugin", version = "1.1.7" }
mapping-io = { group = "net.fabricmc", name = "mapping-io", version = "0.9.1" }

[plugins]
outlet = { id = "io.github.dexman545.outlet", version = "1.8.0" }