# I'm using 1.18.1 instead of 1.18, because I see 1.18.1 as a sort of hotfix instead of a minor update. And this kind of prevents log4shell in a theoretical never possible scenario
mcVersion=1.18.1
javaVersion=17
symbol=MC_1_18_1
supportedMcVersions=>=1.18-beta.8 <1.20.5-alpha.24.14.a
namespace=official